name: Verible formatter
on:
  pull_request_target:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Verible formatter action
        uses: chipsalliance/verible-formatter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./Sim/hdl/common/**/*.{v,sv}
            ./Sim/test/**/*.{v,sv}
          parameters: |
            --inplace
            --indentation_spaces=4
            --module_net_variable_alignment=preserve
            --case_items_alignment=preserve
            --assignment_statement_alignment=preserve
            --compact_indexing_and_selections=true
